//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modules() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Modules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 辅料管理 的本地化字符串。
        /// </summary>
        internal static string AccessoriesManagement {
            get {
                return ResourceManager.GetString("AccessoriesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅料管理 的本地化字符串。
        /// </summary>
        internal static string AccessoryManagement {
            get {
                return ResourceManager.GetString("AccessoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增辅料料号 的本地化字符串。
        /// </summary>
        internal static string AccessoryPartAdd {
            get {
                return ResourceManager.GetString("AccessoryPartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除辅料料号 的本地化字符串。
        /// </summary>
        internal static string AccessoryPartDelete {
            get {
                return ResourceManager.GetString("AccessoryPartDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑辅料料号 的本地化字符串。
        /// </summary>
        internal static string AccessoryPartEdit {
            get {
                return ResourceManager.GetString("AccessoryPartEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辅料料号维护 的本地化字符串。
        /// </summary>
        internal static string AccessoryPartList {
            get {
                return ResourceManager.GetString("AccessoryPartList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位认证 的本地化字符串。
        /// </summary>
        internal static string Account_Certification {
            get {
                return ResourceManager.GetString("Account_Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织架构 的本地化字符串。
        /// </summary>
        internal static string Account_Organization {
            get {
                return ResourceManager.GetString("Account_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        internal static string Account_Popedom {
            get {
                return ResourceManager.GetString("Account_Popedom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string Account_Role {
            get {
                return ResourceManager.GetString("Account_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string Account_User {
            get {
                return ResourceManager.GetString("Account_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商帐号管理 的本地化字符串。
        /// </summary>
        internal static string Account_UserOfSupplier {
            get {
                return ResourceManager.GetString("Account_UserOfSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常管理 的本地化字符串。
        /// </summary>
        internal static string AnormalManagement {
            get {
                return ResourceManager.GetString("AnormalManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽样方案管理 的本地化字符串。
        /// </summary>
        internal static string AQLPlan {
            get {
                return ResourceManager.GetString("AQLPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动排产 的本地化字符串。
        /// </summary>
        internal static string Automatic_Scheduling {
            get {
                return ResourceManager.GetString("Automatic_Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务维护 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Activities {
            get {
                return ResourceManager.GetString("BasalInfo_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常维护 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Anormal {
            get {
                return ResourceManager.GetString("BasalInfo_Anormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户信息 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Customer {
            get {
                return ResourceManager.GetString("BasalInfo_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测项管理 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Detection {
            get {
                return ResourceManager.GetString("BasalInfo_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件配置 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_EmailConfig {
            get {
                return ResourceManager.GetString("BasalInfo_EmailConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Equipment {
            get {
                return ResourceManager.GetString("BasalInfo_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据扩展 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_ExtensionFields {
            get {
                return ResourceManager.GetString("BasalInfo_ExtensionFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 叫料管理 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_ItemType {
            get {
                return ResourceManager.GetString("BasalInfo_ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签管理 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Labels {
            get {
                return ResourceManager.GetString("BasalInfo_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不良代码 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_NCCode {
            get {
                return ResourceManager.GetString("BasalInfo_NCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品信息 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Product {
            get {
                return ResourceManager.GetString("BasalInfo_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源维护 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Resource {
            get {
                return ResourceManager.GetString("BasalInfo_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程维护 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Router {
            get {
                return ResourceManager.GetString("BasalInfo_Router", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列号规则 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_SerialNumber {
            get {
                return ResourceManager.GetString("BasalInfo_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序维护 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Station {
            get {
                return ResourceManager.GetString("BasalInfo_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商管理 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Supplier {
            get {
                return ResourceManager.GetString("BasalInfo_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周转工具 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Turnover {
            get {
                return ResourceManager.GetString("BasalInfo_Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务开发 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_UIDesigner {
            get {
                return ResourceManager.GetString("BasalInfo_UIDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位维护管理 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Unit {
            get {
                return ResourceManager.GetString("BasalInfo_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库信息 的本地化字符串。
        /// </summary>
        internal static string BasalInfo_Warehouse {
            get {
                return ResourceManager.GetString("BasalInfo_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装管理 的本地化字符串。
        /// </summary>
        internal static string BasalInf_Container {
            get {
                return ResourceManager.GetString("BasalInf_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端配置 的本地化字符串。
        /// </summary>
        internal static string Client_Configuration {
            get {
                return ResourceManager.GetString("Client_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端扫描 的本地化字符串。
        /// </summary>
        internal static string Client_Scanner {
            get {
                return ResourceManager.GetString("Client_Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单管理 的本地化字符串。
        /// </summary>
        internal static string CustomMenu {
            get {
                return ResourceManager.GetString("CustomMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        internal static string DataTypeManage {
            get {
                return ResourceManager.GetString("DataTypeManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据管理 的本地化字符串。
        /// </summary>
        internal static string Data_Synchronization {
            get {
                return ResourceManager.GetString("Data_Synchronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIP包装管理 的本地化字符串。
        /// </summary>
        internal static string DIPPackaging_Management {
            get {
                return ResourceManager.GetString("DIPPackaging_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备预警 的本地化字符串。
        /// </summary>
        internal static string EquipmentEarlyWarning {
            get {
                return ResourceManager.GetString("EquipmentEarlyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备点检 的本地化字符串。
        /// </summary>
        internal static string EquipmentInspection {
            get {
                return ResourceManager.GetString("EquipmentInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备基础数据管理 的本地化字符串。
        /// </summary>
        internal static string Equipment_Basic {
            get {
                return ResourceManager.GetString("Equipment_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备校验 的本地化字符串。
        /// </summary>
        internal static string Equipment_CheckOut {
            get {
                return ResourceManager.GetString("Equipment_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string Equipment_Equipment {
            get {
                return ResourceManager.GetString("Equipment_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模治具管理 的本地化字符串。
        /// </summary>
        internal static string Equipment_Mould {
            get {
                return ResourceManager.GetString("Equipment_Mould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工厂信息 的本地化字符串。
        /// </summary>
        internal static string FactoryManage {
            get {
                return ResourceManager.GetString("FactoryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 形态转换 的本地化字符串。
        /// </summary>
        internal static string FormChange {
            get {
                return ResourceManager.GetString("FormChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验方法列表 的本地化字符串。
        /// </summary>
        internal static string InspectionmethodsList {
            get {
                return ResourceManager.GetString("InspectionmethodsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验报告管理 的本地化字符串。
        /// </summary>
        internal static string InspectionOrderAudit {
            get {
                return ResourceManager.GetString("InspectionOrderAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string IQCRecive {
            get {
                return ResourceManager.GetString("IQCRecive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工装夹具 的本地化字符串。
        /// </summary>
        internal static string JigManage {
            get {
                return ResourceManager.GetString("JigManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看板基本信息维护 的本地化字符串。
        /// </summary>
        internal static string Kanban_Basal {
            get {
                return ResourceManager.GetString("Kanban_Basal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级看板 的本地化字符串。
        /// </summary>
        internal static string Kanban_Builtin {
            get {
                return ResourceManager.GetString("Kanban_Builtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看板下发 的本地化字符串。
        /// </summary>
        internal static string Kanban_TagSend {
            get {
                return ResourceManager.GetString("Kanban_TagSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发料管理 的本地化字符串。
        /// </summary>
        internal static string MaterialApply {
            get {
                return ResourceManager.GetString("MaterialApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库盘点 的本地化字符串。
        /// </summary>
        internal static string MaterialCheck {
            get {
                return ResourceManager.GetString("MaterialCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收料管理 的本地化字符串。
        /// </summary>
        internal static string MaterialReceive {
            get {
                return ResourceManager.GetString("MaterialReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退料管理 的本地化字符串。
        /// </summary>
        internal static string MaterialReturn {
            get {
                return ResourceManager.GetString("MaterialReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IQC检验 的本地化字符串。
        /// </summary>
        internal static string Material_IQCFormCheck {
            get {
                return ResourceManager.GetString("Material_IQCFormCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料管理 的本地化字符串。
        /// </summary>
        internal static string Material_Manager {
            get {
                return ResourceManager.GetString("Material_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料入库打印 的本地化字符串。
        /// </summary>
        internal static string Material_MaterialStoragePrint {
            get {
                return ResourceManager.GetString("Material_MaterialStoragePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废管理 的本地化字符串。
        /// </summary>
        internal static string Material_Scrap {
            get {
                return ResourceManager.GetString("Material_Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调拨管理 的本地化字符串。
        /// </summary>
        internal static string Material_Transfers {
            get {
                return ResourceManager.GetString("Material_Transfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品入库 的本地化字符串。
        /// </summary>
        internal static string Mobile_FinishedProductInStorage {
            get {
                return ResourceManager.GetString("Mobile_FinishedProductInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动端-模块入库 的本地化字符串。
        /// </summary>
        internal static string Mobile_FinishedProductInStorageAdd {
            get {
                return ResourceManager.GetString("Mobile_FinishedProductInStorageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品出货 的本地化字符串。
        /// </summary>
        internal static string Mobile_FinishProdShipment {
            get {
                return ResourceManager.GetString("Mobile_FinishProdShipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料管理 的本地化字符串。
        /// </summary>
        internal static string Mobile_Material {
            get {
                return ResourceManager.GetString("Mobile_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料入库 的本地化字符串。
        /// </summary>
        internal static string Mobile_MaterialInStorage {
            get {
                return ResourceManager.GetString("Mobile_MaterialInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产管理 的本地化字符串。
        /// </summary>
        internal static string Mobile_Production {
            get {
                return ResourceManager.GetString("Mobile_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前加工管理 的本地化字符串。
        /// </summary>
        internal static string MoldingManagement {
            get {
                return ResourceManager.GetString("MoldingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务导航管理 的本地化字符串。
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单维护 的本地化字符串。
        /// </summary>
        internal static string Order_ShopOrder {
            get {
                return ResourceManager.GetString("Order_ShopOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序段时间管理 的本地化字符串。
        /// </summary>
        internal static string OSPManagement {
            get {
                return ResourceManager.GetString("OSPManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string PDAEquimentManage {
            get {
                return ResourceManager.GetString("PDAEquimentManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表看板管理 的本地化字符串。
        /// </summary>
        internal static string PDAKanBanManage {
            get {
                return ResourceManager.GetString("PDAKanBanManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PDAManage {
            get {
                return ResourceManager.GetString("PDAManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产管理 的本地化字符串。
        /// </summary>
        internal static string PDAProductionManage {
            get {
                return ResourceManager.GetString("PDAProductionManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品质管理 的本地化字符串。
        /// </summary>
        internal static string PDAQualityManage {
            get {
                return ResourceManager.GetString("PDAQualityManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库管理 的本地化字符串。
        /// </summary>
        internal static string PDAWarehouseManage {
            get {
                return ResourceManager.GetString("PDAWarehouseManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 形态转换 的本地化字符串。
        /// </summary>
        internal static string PDA_FormChange {
            get {
                return ResourceManager.GetString("PDA_FormChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ERP形态转换接口 的本地化字符串。
        /// </summary>
        internal static string PDA_MesToErpChange {
            get {
                return ResourceManager.GetString("PDA_MesToErpChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品变更 的本地化字符串。
        /// </summary>
        internal static string ProductChange {
            get {
                return ResourceManager.GetString("ProductChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产数据配置 的本地化字符串。
        /// </summary>
        internal static string ProductionDataConfig {
            get {
                return ResourceManager.GetString("ProductionDataConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产数据配置 的本地化字符串。
        /// </summary>
        internal static string ProductionDataConfiguration {
            get {
                return ResourceManager.GetString("ProductionDataConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产班次 的本地化字符串。
        /// </summary>
        internal static string ProductionShift {
            get {
                return ResourceManager.GetString("ProductionShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序采集单 的本地化字符串。
        /// </summary>
        internal static string Production_CollectForm {
            get {
                return ResourceManager.GetString("Production_CollectForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备接口 的本地化字符串。
        /// </summary>
        internal static string Production_DeviceInterface {
            get {
                return ResourceManager.GetString("Production_DeviceInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ESOP管理 的本地化字符串。
        /// </summary>
        internal static string Production_ESOP {
            get {
                return ResourceManager.GetString("Production_ESOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品出货 的本地化字符串。
        /// </summary>
        internal static string Production_FinishProdShipMent {
            get {
                return ResourceManager.GetString("Production_FinishProdShipMent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品出货明细 的本地化字符串。
        /// </summary>
        internal static string Production_FinishProdShipMentDetail {
            get {
                return ResourceManager.GetString("Production_FinishProdShipMentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品出库 的本地化字符串。
        /// </summary>
        internal static string Production_FinishProdShipMentList {
            get {
                return ResourceManager.GetString("Production_FinishProdShipMentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品入库 的本地化字符串。
        /// </summary>
        internal static string Production_FinishProductInStorage {
            get {
                return ResourceManager.GetString("Production_FinishProductInStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QHold管理 的本地化字符串。
        /// </summary>
        internal static string Production_Hold {
            get {
                return ResourceManager.GetString("Production_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子看板 的本地化字符串。
        /// </summary>
        internal static string Production_Kanban {
            get {
                return ResourceManager.GetString("Production_Kanban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线别仓管理 的本地化字符串。
        /// </summary>
        internal static string Production_LineEdgeWarehouse {
            get {
                return ResourceManager.GetString("Production_LineEdgeWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备保养 的本地化字符串。
        /// </summary>
        internal static string Production_Maintenance {
            get {
                return ResourceManager.GetString("Production_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品追溯 的本地化字符串。
        /// </summary>
        internal static string Production_Manufacture {
            get {
                return ResourceManager.GetString("Production_Manufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料管理 的本地化字符串。
        /// </summary>
        internal static string Production_Material {
            get {
                return ResourceManager.GetString("Production_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库数据配置 的本地化字符串。
        /// </summary>
        internal static string Production_MaterialConfig {
            get {
                return ResourceManager.GetString("Production_MaterialConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料配送 的本地化字符串。
        /// </summary>
        internal static string Production_MaterialDelivery {
            get {
                return ResourceManager.GetString("Production_MaterialDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSD管理 的本地化字符串。
        /// </summary>
        internal static string Production_MSD {
            get {
                return ResourceManager.GetString("Production_MSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装打印 的本地化字符串。
        /// </summary>
        internal static string Production_PackPrint {
            get {
                return ResourceManager.GetString("Production_PackPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产排产 的本地化字符串。
        /// </summary>
        internal static string Production_Plan {
            get {
                return ResourceManager.GetString("Production_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加工流程单 的本地化字符串。
        /// </summary>
        internal static string Production_ProcessForm {
            get {
                return ResourceManager.GetString("Production_ProcessForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产返工 的本地化字符串。
        /// </summary>
        internal static string Production_Rework {
            get {
                return ResourceManager.GetString("Production_Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产排产 的本地化字符串。
        /// </summary>
        internal static string Production_Schedule {
            get {
                return ResourceManager.GetString("Production_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货管理 的本地化字符串。
        /// </summary>
        internal static string Production_Shipment {
            get {
                return ResourceManager.GetString("Production_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码打印 的本地化字符串。
        /// </summary>
        internal static string Production_SNPrint {
            get {
                return ResourceManager.GetString("Production_SNPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具管理 的本地化字符串。
        /// </summary>
        internal static string Production_Sparepart {
            get {
                return ResourceManager.GetString("Production_Sparepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 追溯记录 的本地化字符串。
        /// </summary>
        internal static string Production_TraceForm {
            get {
                return ResourceManager.GetString("Production_TraceForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据采集模板 的本地化字符串。
        /// </summary>
        internal static string Product_CollectionTemplate {
            get {
                return ResourceManager.GetString("Product_CollectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常用功能 的本地化字符串。
        /// </summary>
        internal static string Product_CollectionTemplate_Control {
            get {
                return ResourceManager.GetString("Product_CollectionTemplate_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计件标准维护 的本地化字符串。
        /// </summary>
        internal static string Product_PieceWage {
            get {
                return ResourceManager.GetString("Product_PieceWage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商管理 的本地化字符串。
        /// </summary>
        internal static string Product_SuplierMaterialManage {
            get {
                return ResourceManager.GetString("Product_SuplierMaterialManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检验标准管理 的本地化字符串。
        /// </summary>
        internal static string QCManagement {
            get {
                return ResourceManager.GetString("QCManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QC信息管理 的本地化字符串。
        /// </summary>
        internal static string Quality_QC {
            get {
                return ResourceManager.GetString("Quality_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽检规则 的本地化字符串。
        /// </summary>
        internal static string Quality_SamplingRule {
            get {
                return ResourceManager.GetString("Quality_SamplingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报废管理 的本地化字符串。
        /// </summary>
        internal static string Quality_SNScrap {
            get {
                return ResourceManager.GetString("Quality_SNScrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPC管理 的本地化字符串。
        /// </summary>
        internal static string Quality_SPC {
            get {
                return ResourceManager.GetString("Quality_SPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预警配置管理 的本地化字符串。
        /// </summary>
        internal static string Quality_WarnSettings {
            get {
                return ResourceManager.GetString("Quality_WarnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 效率报表 的本地化字符串。
        /// </summary>
        internal static string Report_Efficiency {
            get {
                return ResourceManager.GetString("Report_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他报表 的本地化字符串。
        /// </summary>
        internal static string Report_Other {
            get {
                return ResourceManager.GetString("Report_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产报表 的本地化字符串。
        /// </summary>
        internal static string Report_Production {
            get {
                return ResourceManager.GetString("Report_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量报表 的本地化字符串。
        /// </summary>
        internal static string Report_Quality {
            get {
                return ResourceManager.GetString("Report_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表类型 的本地化字符串。
        /// </summary>
        internal static string Report_ReportType {
            get {
                return ResourceManager.GetString("Report_ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表模板 的本地化字符串。
        /// </summary>
        internal static string Report_Template {
            get {
                return ResourceManager.GetString("Report_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板列表 的本地化字符串。
        /// </summary>
        internal static string Report_TemplateList {
            get {
                return ResourceManager.GetString("Report_TemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RMA管理 的本地化字符串。
        /// </summary>
        internal static string RMAManager {
            get {
                return ResourceManager.GetString("RMAManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品点检管理 的本地化字符串。
        /// </summary>
        internal static string SampleNumberManagement {
            get {
                return ResourceManager.GetString("SampleNumberManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工段与线别关系 的本地化字符串。
        /// </summary>
        internal static string Section_ResourceView {
            get {
                return ResourceManager.GetString("Section_ResourceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品出入库 的本地化字符串。
        /// </summary>
        internal static string Shipments {
            get {
                return ResourceManager.GetString("Shipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMT设备 的本地化字符串。
        /// </summary>
        internal static string SMTMachineManage {
            get {
                return ResourceManager.GetString("SMTMachineManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上料管理 的本地化字符串。
        /// </summary>
        internal static string SMTTraceabilityManagement {
            get {
                return ResourceManager.GetString("SMTTraceabilityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准排产 的本地化字符串。
        /// </summary>
        internal static string Standard_Scheduling {
            get {
                return ResourceManager.GetString("Standard_Scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钢网维护 的本地化字符串。
        /// </summary>
        internal static string SteelMeshManage {
            get {
                return ResourceManager.GetString("SteelMeshManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商考核 的本地化字符串。
        /// </summary>
        internal static string SupplierExame {
            get {
                return ResourceManager.GetString("SupplierExame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据接口 的本地化字符串。
        /// </summary>
        internal static string SystemInfo_DataInterface {
            get {
                return ResourceManager.GetString("SystemInfo_DataInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string System_Configuration {
            get {
                return ResourceManager.GetString("System_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掩码管理 的本地化字符串。
        /// </summary>
        internal static string ValidationMaskManage {
            get {
                return ResourceManager.GetString("ValidationMaskManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警报管理 的本地化字符串。
        /// </summary>
        internal static string Warning_Management {
            get {
                return ResourceManager.GetString("Warning_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车间维护 的本地化字符串。
        /// </summary>
        internal static string WorkShopManage {
            get {
                return ResourceManager.GetString("WorkShopManage", resourceCulture);
            }
        }
    }
}
