//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubSystems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubSystems() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SubSystems", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 基础数据 的本地化字符串。
        /// </summary>
        internal static string LeanMES_BasalInfo {
            get {
                return ResourceManager.GetString("LeanMES_BasalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据采集 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Collection {
            get {
                return ResourceManager.GetString("LeanMES_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二次开发 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Custom {
            get {
                return ResourceManager.GetString("LeanMES_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Equipment {
            get {
                return ResourceManager.GetString("LeanMES_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 看板管理 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Kanban {
            get {
                return ResourceManager.GetString("LeanMES_Kanban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LeanMES移动端 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Mobile {
            get {
                return ResourceManager.GetString("LeanMES_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDA管理 的本地化字符串。
        /// </summary>
        internal static string LeanMES_PDA {
            get {
                return ResourceManager.GetString("LeanMES_PDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产管理 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Production {
            get {
                return ResourceManager.GetString("LeanMES_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品质管理 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Quality {
            get {
                return ResourceManager.GetString("LeanMES_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BI中心 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Report {
            get {
                return ResourceManager.GetString("LeanMES_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库管理 的本地化字符串。
        /// </summary>
        internal static string LeanMES_Store {
            get {
                return ResourceManager.GetString("LeanMES_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        internal static string SYS_SystemInfo {
            get {
                return ResourceManager.GetString("SYS_SystemInfo", resourceCulture);
            }
        }
    }
}
