//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enum() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Enum", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全检 的本地化字符串。
        /// </summary>
        internal static string AllCheck {
            get {
                return ResourceManager.GetString("AllCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是 的本地化字符串。
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次通过 的本地化字符串。
        /// </summary>
        internal static string BatchPass {
            get {
                return ResourceManager.GetString("BatchPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次退货 的本地化字符串。
        /// </summary>
        internal static string BatchReturn {
            get {
                return ResourceManager.GetString("BatchReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --请选择-- 的本地化字符串。
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭的 的本地化字符串。
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件已冻结 的本地化字符串。
        /// </summary>
        internal static string Component_Hold {
            get {
                return ResourceManager.GetString("Component_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让步使用 的本地化字符串。
        /// </summary>
        internal static string ConcessionUse {
            get {
                return ResourceManager.GetString("ConcessionUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装箱号 的本地化字符串。
        /// </summary>
        internal static string Container_Number {
            get {
                return ResourceManager.GetString("Container_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户条码 的本地化字符串。
        /// </summary>
        internal static string CustomerSN {
            get {
                return ResourceManager.GetString("CustomerSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户订单 的本地化字符串。
        /// </summary>
        internal static string Customer_Order {
            get {
                return ResourceManager.GetString("Customer_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每天 的本地化字符串。
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钉钉 的本地化字符串。
        /// </summary>
        internal static string DingTalk {
            get {
                return ResourceManager.GetString("DingTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不可使用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ECO号码 的本地化字符串。
        /// </summary>
        internal static string ECO_Number {
            get {
                return ResourceManager.GetString("ECO_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可使用 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工程 的本地化字符串。
        /// </summary>
        internal static string Engineering {
            get {
                return ResourceManager.GetString("Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 免检 的本地化字符串。
        /// </summary>
        internal static string ExemptionCheck {
            get {
                return ResourceManager.GetString("ExemptionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成品加工流程单 的本地化字符串。
        /// </summary>
        internal static string FinishedProcessing {
            get {
                return ResourceManager.GetString("FinishedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        internal static string Frozen {
            get {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领用 的本地化字符串。
        /// </summary>
        internal static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让步通过 的本地化字符串。
        /// </summary>
        internal static string GiveInPass {
            get {
                return ResourceManager.GetString("GiveInPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持有 的本地化字符串。
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold Consec NC 的本地化字符串。
        /// </summary>
        internal static string Hold_Consec_NC {
            get {
                return ResourceManager.GetString("Hold_Consec_NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold SPC Viol 的本地化字符串。
        /// </summary>
        internal static string Hold_SPC_Viol {
            get {
                return ResourceManager.GetString("Hold_SPC_Viol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold SPC Warn 的本地化字符串。
        /// </summary>
        internal static string Hold_SPC_Warn {
            get {
                return ResourceManager.GetString("Hold_SPC_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold Yield Rate 的本地化字符串。
        /// </summary>
        internal static string Hold_Yield_Rate {
            get {
                return ResourceManager.GetString("Hold_Yield_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incident Number 的本地化字符串。
        /// </summary>
        internal static string Incident_Number {
            get {
                return ResourceManager.GetString("Incident_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入仓 的本地化字符串。
        /// </summary>
        internal static string InComing {
            get {
                return ResourceManager.GetString("InComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory Receipt 的本地化字符串。
        /// </summary>
        internal static string Inventory_Receipt {
            get {
                return ResourceManager.GetString("Inventory_Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IQC检验单号 的本地化字符串。
        /// </summary>
        internal static string IQC_Number {
            get {
                return ResourceManager.GetString("IQC_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造 的本地化字符串。
        /// </summary>
        internal static string Manufactured {
            get {
                return ResourceManager.GetString("Manufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造/采购 的本地化字符串。
        /// </summary>
        internal static string Manufactured_Purchased {
            get {
                return ResourceManager.GetString("Manufactured_Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产警报 的本地化字符串。
        /// </summary>
        internal static string ManufactureWarning {
            get {
                return ResourceManager.GetString("ManufactureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料条码 的本地化字符串。
        /// </summary>
        internal static string MaterialBarCode {
            get {
                return ResourceManager.GetString("MaterialBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料条码 的本地化字符串。
        /// </summary>
        internal static string Material_GRN {
            get {
                return ResourceManager.GetString("Material_GRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每月 的本地化字符串。
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从不 的本地化字符串。
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无计划 的本地化字符串。
        /// </summary>
        internal static string Non_scheduled {
            get {
                return ResourceManager.GetString("Non_scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常打印 的本地化字符串。
        /// </summary>
        internal static string NormalPrint {
            get {
                return ResourceManager.GetString("NormalPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检查 的本地化字符串。
        /// </summary>
        internal static string NotCheck {
            get {
                return ResourceManager.GetString("NotCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未完成 的本地化字符串。
        /// </summary>
        internal static string NotComplete {
            get {
                return ResourceManager.GetString("NotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OBA Batch 的本地化字符串。
        /// </summary>
        internal static string OBA_Batch {
            get {
                return ResourceManager.GetString("OBA_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过时的 的本地化字符串。
        /// </summary>
        internal static string Obsolete {
            get {
                return ResourceManager.GetString("Obsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单条码 的本地化字符串。
        /// </summary>
        internal static string OrderBarCode {
            get {
                return ResourceManager.GetString("OrderBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装条码 的本地化字符串。
        /// </summary>
        internal static string PackagingBarCode {
            get {
                return ResourceManager.GetString("PackagingBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栈板条码 的本地化字符串。
        /// </summary>
        internal static string PalletBarCode {
            get {
                return ResourceManager.GetString("PalletBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抽检 的本地化字符串。
        /// </summary>
        internal static string PartCheck {
            get {
                return ResourceManager.GetString("PartCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可释放 的本地化字符串。
        /// </summary>
        internal static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Lot 的本地化字符串。
        /// </summary>
        internal static string Process_Lot {
            get {
                return ResourceManager.GetString("Process_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Productive 的本地化字符串。
        /// </summary>
        internal static string Productive {
            get {
                return ResourceManager.GetString("Productive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采购 的本地化字符串。
        /// </summary>
        internal static string Purchased {
            get {
                return ResourceManager.GetString("Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合格 的本地化字符串。
        /// </summary>
        internal static string Qualified {
            get {
                return ResourceManager.GetString("Qualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品质警报 的本地化字符串。
        /// </summary>
        internal static string QualityWarning {
            get {
                return ResourceManager.GetString("QualityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收料单号 的本地化字符串。
        /// </summary>
        internal static string Receipt_Number {
            get {
                return ResourceManager.GetString("Receipt_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未排产 的本地化字符串。
        /// </summary>
        internal static string Releasable {
            get {
                return ResourceManager.GetString("Releasable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修 的本地化字符串。
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重打 的本地化字符串。
        /// </summary>
        internal static string Reprint {
            get {
                return ResourceManager.GetString("Reprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退货 的本地化字符串。
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RMA号码 的本地化字符串。
        /// </summary>
        internal static string RMA_Number {
            get {
                return ResourceManager.GetString("RMA_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled Down 的本地化字符串。
        /// </summary>
        internal static string Scheduled_Down {
            get {
                return ResourceManager.GetString("Scheduled_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品条码 的本地化字符串。
        /// </summary>
        internal static string SFC_Release {
            get {
                return ResourceManager.GetString("SFC_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SFC Serialize 的本地化字符串。
        /// </summary>
        internal static string SFC_Serialize {
            get {
                return ResourceManager.GetString("SFC_Serialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工单号 的本地化字符串。
        /// </summary>
        internal static string Shop_Order {
            get {
                return ResourceManager.GetString("Shop_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slot Configuration 的本地化字符串。
        /// </summary>
        internal static string Slot_Configuration {
            get {
                return ResourceManager.GetString("Slot_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信 的本地化字符串。
        /// </summary>
        internal static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standby 的本地化字符串。
        /// </summary>
        internal static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统警报 的本地化字符串。
        /// </summary>
        internal static string SystemWarning {
            get {
                return ResourceManager.GetString("SystemWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半成品加工流程单 的本地化字符串。
        /// </summary>
        internal static string UnfinishedProcessing {
            get {
                return ResourceManager.GetString("UnfinishedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不合格 的本地化字符串。
        /// </summary>
        internal static string UnQualified {
            get {
                return ResourceManager.GetString("UnQualified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unscheduled Down 的本地化字符串。
        /// </summary>
        internal static string Unscheduled_Down {
            get {
                return ResourceManager.GetString("Unscheduled_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待检 的本地化字符串。
        /// </summary>
        internal static string WaitCheck {
            get {
                return ResourceManager.GetString("WaitCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库警报 的本地化字符串。
        /// </summary>
        internal static string WareHouseWarning {
            get {
                return ResourceManager.GetString("WareHouseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        internal static string WebClient {
            get {
                return ResourceManager.GetString("WebClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        internal static string WeChat {
            get {
                return ResourceManager.GetString("WeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每周 的本地化字符串。
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸣声 的本地化字符串。
        /// </summary>
        internal static string Whistle {
            get {
                return ResourceManager.GetString("Whistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每年 的本地化字符串。
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
    }
}
